# Generated by Django 4.2.16 on 2024-09-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='called',
            field=models.BooleanField(default=False, verbose_name='Foi chamado'),
        ),
    ]
